#!/usr/bin/env python3
import argparse, os, shutil, subprocess, io
from subprocess import Popen
from shlex import quote
from os import path

def relative(subpath=''):
	from os import path
	return path.join(path.dirname(path.abspath(__file__)), subpath)

def fileContainsChunk(filePath, searchedChunk):
	try:
		fd = open(filePath)
		contents = fd.read()
		fd.close()
		return searchedChunk in contents
	except FileNotFoundError:
		return False

dotfilesEntryFilename = 'install'
dotfilesTargetDirectoryPathWithHome = '$HOME/dotfiles'
dotfilesTargetDirectoryPathWithExpansion = '~/dotfiles'
dotfilesTargetDirectoryPath = os.path.expanduser(dotfilesTargetDirectoryPathWithExpansion)
parser = argparse.ArgumentParser(description='Installs dotfiles in the system. To uninstall dotfiles later, delete {} and remove the reference to the deleted directory from "target".'.format(dotfilesTargetDirectoryPath))
defaultTargetSystemFilePath = '~/.zshrc'

parser.add_argument(
	'source', 
	help='Path to directory containing dotfiles. Run this command with the same path to pick up changes in dotfiles and apply new files to the system configuration. Directory contents will be copied to "{}". Dotfiles directory must contain a "{}" file which will be sourced by the system.'.format(dotfilesTargetDirectoryPath, dotfilesEntryFilename)
)

parser.add_argument(
	'target', 
	help='Operating system file to append dotfiles to. For example, "~/.zshrc" or "~/.profile". If the file doesn\'t exist, it will be created. If no target is provided, the default will be used (~/.zshrc).', 
	nargs='?',
	default=defaultTargetSystemFilePath
)

parser.add_argument(
	'-t', 
	'--temporary', 
	help='If specified, the script will only copy dotfiles to "{}". Otherwise, the system will install dotfiles on every boot.'.format(dotfilesTargetDirectoryPath), 
	action='store_true'
)

parser.add_argument(
	'-na',
	'--no-auxiliary',
	help='Do not install recommended auxiliary scripts.',
	action='store_true'
)

args = parser.parse_args()

dotfilesDirectoryPath = os.path.expanduser(args.source)
targetSystemFilePath = os.path.expanduser(args.target)
addToTargetSystemFile = not args.temporary
runAuxiliaryScripts = not args.no_auxiliary

print('Checking if "{}" exists inside dotfiles directory.'.format(dotfilesEntryFilename))
dotfilesInstallPath = os.path.join(dotfilesDirectoryPath, dotfilesEntryFilename)
installExists = os.path.isfile(dotfilesInstallPath)

if not installExists:
	print('Entry file named "{}" is required inside dotfiles directory but was not found at path "{}". It will be run on every system boot.'.format(dotfilesEntryFilename, dotfilesInstallPath))
	exit(1)
else:
	print('Dotfiles install file found.')
print('Copying dotfiles directories\' contents to {}.'.format(dotfilesTargetDirectoryPath))
dotfilesTargetDirectoryExists = os.path.isdir(dotfilesTargetDirectoryPath)
if dotfilesTargetDirectoryExists:
	print('Dotfiles target directory ("{}") already exists. It will be removed and contents from {} will replace it.'.format(dotfilesTargetDirectoryPath, dotfilesDirectoryPath))
	print(dotfilesTargetDirectoryPath)
	shutil.rmtree(dotfilesTargetDirectoryPath)
else:
	print('Dotfiles target directory ("{}") doesn\'t exist yet. It will be created.'.format(dotfilesTargetDirectoryPath))
shutil.copytree(dotfilesDirectoryPath, dotfilesTargetDirectoryPath)
print('{} directory updated.'.format(dotfilesTargetDirectoryPath))
dotfilesDirectoryPathExportCommand = 'export DF_DIR="{}"'.format(dotfilesTargetDirectoryPathWithHome)

if addToTargetSystemFile:
	print('Appending "{}" to system file path so it is always used.'.format(targetSystemFilePath))
	dotfilesTargetInstallFilePath = os.path.join(
		dotfilesTargetDirectoryPathWithHome, 
		dotfilesEntryFilename
	)
	sourceSystemCommand = '. "{}"'.format(dotfilesTargetInstallFilePath)
	sourcingStream = io.StringIO()
	sourcingStream.write(os.linesep)
	sourcingStream.write('######DOTFILES INSTALL START######')
	sourcingStream.write(os.linesep)
	sourcingStream.write(dotfilesDirectoryPathExportCommand)
	sourcingStream.write(os.linesep)
	sourcingStream.write('if [ -f "{}" ]; then'.format(dotfilesTargetInstallFilePath))
	sourcingStream.write(os.linesep)
	sourcingStream.write(sourceSystemCommand)
	sourcingStream.write(os.linesep)
	sourcingStream.write('fi')
	sourcingStream.write(os.linesep)
	sourcingStream.write('######DOTFILES INSTALL FINISH######')
	sourcingStream.write(os.linesep)
	sourcingStream.seek(0)
	dotfilesInstallAlreadyAdded = fileContainsChunk(
		targetSystemFilePath, 
		sourcingStream.getvalue()
	)

	if dotfilesInstallAlreadyAdded:
		print('Dotfiles already installed in system. Not installing again.')
	else:
		print('Installing dotfiles in system.')
		with open(targetSystemFilePath, 'a') as systemFile:
			shutil.copyfileobj(sourcingStream, systemFile)

sourceTargetSystemFilePath = '. "{}"'.format(targetSystemFilePath)

def install(scriptPath):
	print('Installing "{}".'.format(scriptPath))
	process = Popen(quote(relative(path.expanduser(scriptPath))), shell=True)
	process.communicate()
	processReturnCode = process.returncode

	if processReturnCode == 0:
		print('Installed "{}"'.format(scriptPath))
	else:
		raise Exception('There was an error during install (file "{}", exit code {}).'
			.format(scriptPath, processReturnCode))

if runAuxiliaryScripts:
	print('Running recommended auxiliary scripts.')
	install('./installations/common/6. install zsh and ohmyzsh')
	install('./installations/common/1. add global gitignore rules')
	install('./installations/common/3. set default git editor to nano')

print('To source in current shell, execute \'{}\'.'.format(sourceTargetSystemFilePath))
