#!/usr/bin/env python3
import argparse, os, subprocess
from shlex import quote
from os import path
from glob import glob

def relative(subpath='', useCwd=False):
	import os
	basePath = os.getcwd() if useCwd else os.path.dirname(os.path.abspath(__file__))
	return os.path.normpath(os.path.join(basePath, os.path.expanduser(subpath)))
parser = argparse.ArgumentParser('This script will add all files inside the specified directory and its subdirectories, excluding any files with the extension ".pub", which is the usual name gives to files containing public keys.')
parser.add_argument(
	'path', 
	help='Path to key.'
)
args = parser.parse_args()
keyFilePath = args.path
pathToKey = relative(keyFilePath, True)
subprocess.run('ssh-keygen -l -E md5 -f {} | awk \'{{ print $2 }}\' | cut -c 5-'.format(quote(pathToKey)), shell=True, check=True)