#!/usr/bin/env python3
import argparse, os, subprocess
from shlex import quote
from os import path
from glob import glob

def relative(subpath='', useCwd=False):
	import os
	basePath = os.getcwd() if useCwd else os.path.dirname(os.path.abspath(__file__))
	return os.path.normpath(os.path.join(basePath, os.path.expanduser(subpath)))
parser = argparse.ArgumentParser('Creates a standard RSA key inside the provided file. Will also generate a .pub file alongside the private key containing the public key for it. No passphrase will be used for the new key.')
parser.add_argument(
	'path', 
	help='Path to the key.'
)
args = parser.parse_args()
newKeyPath = args.path
pathToKey = relative(newKeyPath, True)
subprocess.run('ssh-keygen -q -t rsa -f {} -N \'\''.format(quote(pathToKey)), shell=True, check=True)
print('Generated key at {}(.pub).'.format(quote(pathToKey)))